### ISSUE TITLE
Wrong codesendbox (Using Transporter to Communicate with a Service Worker)

### ISSUE THREAD

**Issue by danielkleinert** [daniel-nagy/transporter#8]
Hey there,

It appears to me like the codesendbox for the service worker (https://codesandbox.io/p/devbox/transporter-service-worker-example-d43prv) is the same as the one for the todo app and doesn't register a service worker at all. 

I may be dumb or blind or booth, but could you have a look at that?

**Comment by daniel-nagy** [comment]
Thanks for reporting this and sorry for the delayed response! I didn't get a notification for some reason.

The link was indeed wrong. I have updated it. Can you check again?

**Comment by daniel-nagy** [comment]
Going to go ahead and close.
